[package]
name = "shredstream_proxy_client_ts"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.12.2", default-features = false, features = ["napi6", "serde-json", "tokio_rt", "async"] }
napi-derive = "2.12.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tonic = { version = "0.13.1" }
solana-entry = "2.3.4"
solana-message = "2.4.0"
solana-transaction = "2.2.3"
shredstream_proxy_client = { path = "../../crates/shredstream-proxy-client" }
solana_entry_decoder = { path = "../../crates/solana-entry-decoder" }

[build-dependencies]
napi-build = "2.0.1"
