[package]
name = "shredstream_proxy_client_ts"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.12.2", default-features = false, features = ["napi4", "serde-json", "tokio_rt", "async"] }
napi-derive = "2.12.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
shredstream_proxy_client = { path = "../../crates/shredstream-proxy-client" }

[build-dependencies]
napi-build = "2.0.1"
